### ISSUE TITLE
Browser wird nicht richtig beendet

### ISSUE THREAD

**Issue by roehlc** [ewsnaj/gesten#10]
bzgl. Alpha 0.1 binary
Wenn man den Beenden Button benutzt, wird der Browser nicht normal beendet, sodass er bei nächsten Start Funktionen anbietet, die normalerweise angezeigt werden, wenn der Browser abgestürzt ist (z.B. Tabs wiederherstellen). Leider passiert das irgendwie nciht jedes mal. Muss man mal ein wenig ruzmprobieren um genau rauszufinden wann der Fehler auftritt.
![browser nicht richtig beendet](https://user-images.githubusercontent.com/33691485/34081996-b8fd1ad4-e356-11e7-8d2e-e0323621959e.JPG)

**Comment by ewsnaj** [comment]
Wird sich eh noch ändern, da browser nicht geschlossen werden soll, sondern nur der Tab
