### ISSUE TITLE
Aufbereitete NMAP Ergebnisse aktualisieren sich nicht live

### ISSUE THREAD

**Issue by roehlc** [ewsnaj/gesten#11]
Trotz neuer Ergebnisse (offene Ports sind in der Log Ansicht sichtbar), aktualisieren sich die aufbereiteten NMAP Ergebnisse nicht live. Wenn man einmal auf die IP Adresse klickt, dann werden die bis dahin gefunden Ports angezeigt, aber keine weiteren neuen.
1. die IP adresse ist dann kein link mehr (wenn man einfach nochmal auf die IP klicken könnte zum aktualisieren, wäre man schonmal etwas weiter
2. noch besser wäre wenn das sich aktualisiert ohne das man nochmal klicken muss

**Comment by ewsnaj** [comment]
wenn man auf die ip click sollen auch keine nmap ergebnisse angezeigt werden, wenn dann nikto, dirbuster oder eyewitness

**Comment by roehlc** [comment]
Ich meinte damit, wenn man auf die Ergebnisse Seite kommt, werden ja erstmal nur ips in der ip  Spalte angezeigt und noch keine Ports. Wenn man dann auf eine ip klickt werden in der Port Spalte die offenen Ports die bis zu diesem Zeitpunkt zu dieser ip gefunden wurden angezeigt. Wenn aber danach noch neue Ports hinzukommen, dann erscheinen diese nicht automatisch in dieser Liste, sondern nur wenn man die Seite nochmal neu aufruft, dann wieder auf die ip klickt. Ist das nun verständlich? Sonst kann ich es in der Pause von DBWT auch mal eben zeigen.

**Comment by ewsnaj** [comment]
bitte mit neustem release a0.2 ad68090 testen
