### ISSUE TITLE
Firefox aktuellen Tab schließen

### ISSUE THREAD

**Issue by ewsnaj** [ewsnaj/gesten#12]
Kann ja einer von euch mal raus finden, da mein weg des firefox killens ja nicht erwünscht war 🤷‍♂️ 

viel spaß 😘

**Comment by roehlc** [comment]
[Mozilla Developing Network](https://developer.mozilla.org/en-US/docs/Web/API/Window/close)
da steht, das man Fenster schließen kann, die man auch im gleichen Script geöffnet hat. Bin mir aber nicht sicher ob das was wir brauchen damit gemeint ist

**Comment by ewsnaj** [comment]
Korrekt, FENSTER.. dann müsste immer ein neues Fesnter für jede Seite geöffnet werden.
